# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170312_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='famouser',
            name='follows',
            field=models.ManyToManyField(related_name='_famouser_follows_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
