# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('posts', models.ManyToManyField(to='counsel.Question')),
            ],
        ),
    ]
