# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bad_rators',
            field=models.ManyToManyField(related_name='bad_anwers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='good_rators',
            field=models.ManyToManyField(related_name='good_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
