# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0002_auto_20170314_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='updated_date',
        ),
    ]
