# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
