# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0003_auto_20170318_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_accessed_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 11, 14, 57, 203681)),
        ),
    ]
