# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0003_auto_20170312_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
