# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0004_question_last_accessed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_accessed_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 23, 10, 19, 670437)),
        ),
    ]
